### ISSUE TITLE
Drop dependency on deprecated `gulp-util`

### ISSUE THREAD

**Issue by chrissnyder2337** [colinodell/gulp-eol-enforce#2]
`gulp-util` is deprecated. It should be replaced by dependencies on the individual components used by `gulp-eol-enforce`

See: https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5

**Comment by colinodell** [comment]
I also need to fix `require('gulp-util').File;` in `test/main.js`

**Comment by colinodell** [comment]
Just released version 1.0.0 with these changes.  Thanks for your help Chris!
